# kind: ConfigMap
# apiVersion: v1
# metadata:
#   name: frontend
#   namespace: expense
# data:
#   DB_HOST: backend

---

apiVersion: webs/v1
kind: Deployment
metadata:
  name: frontend
  namespace: expense
  # these labels belongs to deplyment resource
  labels:
    project: expense
    component: frontend
    environment: dev
    tier: web
spec:
  # modify replicas according to your case
  replicas: 2
  selector:
    matchLabels:
      project: expense
      component: frontend
      environment: dev
      tier: web
    # below is the pod defination
  template:
    metadata:
      labels:
        project: expense
        component: frontend
        environment: dev
        tier: web
    spec:
      containers:
      - name: frontend
        image: charan466/frontend:1.0.0
        # env:
        #     - name: frontend_ROOT_PASSWORD
        #       value: Expenseweb@1
        # envFrom:
        # - configMapRef:
        #     name: frontend

---

apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: expense
spec:
  type: LoadBalancer
  selector:
    project: expense
    component: frontend
    environment: dev
    tier: web
  ports:
  - protocol: TCP
    port: 80 #service-port
    targetPort: 80 #target-port