apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: expense
  # these labels belongs to deplyment resource
  labels:
    project: expense
    component: mysql
    environment: dev
    tier: db
spec:
  # modify replicas according to your case
  replicas: 20
  selector:
    matchLabels:
      project: expense
      component: mysql
      environment: dev
      tier: db
    # below is the pod defination
  template:
    metadata:
      labels:
        project: expense
        component: mysql
        environment: dev
        tier: db
    spec:
      containers:
      - name: mysql
        image: charan466/mysql:1.0.0